task_vlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vlog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vlog/urls.py
from django.urls import path
from vlog.views import *

urlpatterns = [
    path('', PostsListView.as_view(), name='main'),
    path('login/', Login.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('create/post', PostCreateView.as_view(), name='create'),
    path('mainpost/', MainPostListView.as_view(), name='main_post'),
    path('comment/create/', CreateCommentView.as_view(), name='create_comment'),
    path('comments', CommentListView.as_view(), name='comments'),
    path('delete/post/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('myposts/', MyPostsListView.as_view(), name='my_posts'),
]

vlog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from mptt.models import MPTTModel, TreeForeignKey


class TzUser(AbstractUser):
    email = models.EmailField(max_length=50, blank=True, null=True)
    photo = models.ImageField(upload_to='media', default='defaultphoto.jpg', blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, null=False, blank=False)

    def __str__(self):
        return "{}".format(self.username)


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    picture = models.ImageField(upload_to='media', default='defaultpost.jpg', blank=True, null=True)
    author = models.ForeignKey(TzUser, on_delete=models.CASCADE)

    def __str__(self):
        return "{} by {}".format(self.title, self.author)


class Comments(MPTTModel):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    author = models.ForeignKey(TzUser, on_delete=models.CASCADE)
    parent = TreeForeignKey('self', related_name='children', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.comment)

vlog/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class TzUserForm(ModelForm):
    confirm_pass = forms.CharField(max_length=100)

    class Meta:
        model = TzUser
        fields = ('username', 'photo', 'email', 'password', 'confirm_pass', 'phone_number')

    def clean(self):
        clean_data = super().clean()
        if clean_data.get('password') != clean_data.get('confirm_pass'):
            raise forms.ValidationError('Passwords are not equal!')


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'picture')


class CommentCreateForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('comment',)

vlog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import ListView, CreateView, DeleteView
from django.contrib import messages
from .forms import *


class UserCreateView(CreateView):
    model = TzUser
    form_class = TzUserForm
    success_url = '/login'
    template_name = 'register.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(self.object.password)
        self.object.save()
        return super().form_valid(form)


class Login(LoginView):
    template_name = 'login.html'


class Logout(LoginRequiredMixin, LogoutView):
    next_page = '/'
    login_url = 'login/'


class PostsListView(ListView):
    model = Post
    template_name = 'main.html'
    login_url = 'login/'


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login/'
    form_class = PostCreateForm
    success_url = '/'
    template_name = 'postcreate.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        messages.add_message(self.request, messages.INFO, 'Пост успешно создан')
        obj.save()
        return super().form_valid(form=form)


class MainPostListView(ListView):
    model = Post
    template_name = 'mainpost.html'
    login_url = 'login/'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.request.GET['post_id'])


class CreateCommentView(CreateView):
    form_class = CommentCreateForm
    success_url = '/'

    def form_valid(self, form):
        object = form.save(commit=False)
        object.post_id = self.request.POST['post_id']
        object.author_id = self.request.POST['author_id']
        if self.request.POST['parent_id']:
            object.parent_id = self.request.POST['parent_id']
        object.save()
        return super().form_valid(form=form)


class CommentListView(ListView):
    model = Comments
    template_name = 'comments.html'
    login_url = 'login/'
    paginate_by = 15
    extra_context = {'comment_form': CommentCreateForm}

    def get_queryset(self):
        qs = Comments.objects.filter(post_id=self.request.GET['post_id'])
        return qs


class DeletePostView(PermissionRequiredMixin, DeleteView):
    model = Post
    permission_required = 'is_superuser'
    success_url = '/'


class MyPostsListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'mypage.html'
    login_url = 'login/'
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)

templates/base.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>Personal cards</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet">
</head>
<body>
<body style="background-color: #333333">
<div>

    {% block content %}
    {% endblock %}
</div>
</body>

templates/comments.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block content %}
    {% if request.user.is_authenticated and not request.user.is_superuser %}
     <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Приветствую, {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                        <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
      {% elif request.user.is_superuser %}
           <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Аккаунт администратора - {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                         <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        <br>
        <a href="{% url 'register' %}">Registration</a>
        <br>
        <br>

{% endif %}
    <br>
        <br>
   <div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>


        <h4 style="color: #e4b101">Комментарии:</h4>

                   <p>   {% if request.user.is_authenticated  %}
  <form style="color: whitesmoke"  method="post" action="{% url 'create_comment' %}">
    {% csrf_token %}

    {{ comment_form }}
    <input type="hidden" name="post_id" value="{{ request.GET.post_id }}">
      <input type="hidden" name="parent_id" value="{{ Null }}">
      <input type="hidden" name="author_id" value="{{ request.user.id}}">
    <button type="submit" class="btn btn-success" value="Purchase"> Оставить коментарий </button>
       <br>
{% endif %}

</form></p>


        {%  recursetree comments_list %}

          <div style="color: whitesmoke">{{node.author}}:<br>{{ node.comment }}  </div>
  {% if request.user.is_authenticated  %}
                            <p><form style="color: whitesmoke"  method="post"
                                     action="{% url 'create_comment' %}">
    {% csrf_token %}

    {{comment_form }}
    <input type="hidden" name="post_id" value="{{ request.GET.post_id }}">
    <input type="hidden" name="parent_id" value="{{ node.id }}">

   <input type="hidden" name="author_id" value="{{ request.user.id}}">
    <button type="submit" class="btn btn-success" value="Purchase"> Комментировать </button>
       <br>
      {% endif %}

</form></p>
<br>

        {% if not node.is_leaf_node %}
       <ul class="children">
                    {{ children }}

                </ul>
        {% endif %}


        {% endrecursetree %}



<nav aria-label="Page navigation example" style="min-height: 100%">
  <ul class="pagination">
   {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}
&post_id={{ request.GET.post_id }}">Previous</a></li>
    {% endif %}
      <li class="page-item"><a class="page-link" href="?page=1&post_id={{ request.GET.post_id }}">1</a></li>
      {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}
&post_id={{ request.GET.post_id }}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}
&post_id={{ request.GET.post_id }}">Last</a></li>
  {% endif %}
  </ul>
</nav>


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div style="color: #e4b101; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%)">

        <form method="post">
            {% csrf_token %}
            {{ form }}
            <div class="col-5">
                <button type="submit" class="btn btn-warning" value="Login"> Login</button>
            </div>
            {{ form.errors }}
        </form>
    </div>
<div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>

{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% block content %}
  <div style="color: #e4b101; position: center; text-align: center">
      <h1>TZ Blog</h1></div>
    <br>

  {% if request.user.is_authenticated and not request.user.is_superuser %}
     <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">You are welcome, {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                        <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
      {% elif request.user.is_superuser %}
           <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Аккаунт администратора - {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                         <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        {% else %}

      <form method="get" action= "{% url 'login'  %}">


                <button type="submit" class="btn btn-warning" value="Update"> Login </button>
            </form>
        <br>

      <form method="get" action= "{% url 'register'  %}">


                <button type="submit" class="btn btn-warning" value="Update"> Registration </button>
            </form>
        <br>
        <br>
{% endif %}
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    <br>
    {% if request.user.is_authenticated %}


        <form method="get" action= "{% url 'create' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Create post </button>
            </form>

            <br>

        <form method="get" action= "{% url 'my_posts'  %}">


                <button type="submit" class="btn btn-warning" value="Update"> Мои посты </button>
            </form>
    {% endif %}
     {% for post in object_list %}

                    <div style="color: whitesmoke">
                        <div class="d-flex">
                            <div class="p-2">
                                <img src="/media/{{ post.picture }}" width="185" height="150">
                            </div>
                            <div class="p-2">
                                <h2 style="color: #e4b101">Тема поста: {{ post.title }}</h2>

                                <p>Автор поста: {{ post.author}}</p>
                                <p> <div>
                                <form method="get" action="{% url 'main_post'  %}">
                                    <input  type="hidden" name="post_id" value="{{ post.pk }}">
                                    <button type="submit" class="btn btn-warning" value="Update"> Перейти на главную страницу поста </button>
                                </form>
                            </div>
                            </p>
                                {% if request.user.is_superuser %}
                                <p><div>
                                <form method="post" action="{% url 'delete_post' post.pk  %}">
                                      {% csrf_token %}
                                    <button type="submit" class="btn btn-warning" value="Update"> Удалить пост </button>
                                </form>

                            </div></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
        <hr style="background-color: #e4b101">
                                {% endfor %}


{% endblock %}

templates/mainpost.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated and not request.user.is_superuser %}
     <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Приветствую, {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                        <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
      {% elif request.user.is_superuser %}
           <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Аккаунт администратора - {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                         <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        <br>
        <a href="{% url 'register' %}">Registration</a>
        <br>
        <br>

{% endif %}
    <br>
        <br>
   <div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>
     {% for post in object_list %}

                    <div style="color: whitesmoke">
                        <div class="d-flex">
                            <div class="p-2">
                                <img src="/media/{{ post.picture }}" width="250" height="170">
                            </div>
                            <div class="p-2">
                                <h2 style="color: #e4b101">{{ post.title }}</h2>
                                <p> {{ post.content}}</p>

                                <p>Автор поста: {{ post.author}}</p>
                            <br>
                            <div class="p-2">



                                <p> <div>
                                <form method="get" action="{% url 'comments'  %}">
                                    <input  type="hidden" name="post_id" value="{{ post.pk }}">
                                    <button type="submit" class="btn btn-warning" value="Update"> Check comments </button>
                                </form>
                            </div>
                            </div>

                            </div>
                        </div>
                    </div>
                                {% endfor %}

{% endblock %}

templates/mypage.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated and not request.user.is_superuser %}
     <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Приветствую, {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                        <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>
      {% elif request.user.is_superuser %}
           <div class="alert alert-warning" role="alert">
                <div class="d-flex">
                    <div class="p-2">Аккаунт администратора - {{ request.user }}!</div>
                    <div class="ml-auto p-2">
                         <form method="get" action="{% url 'logout' %}">
                            <button type="submit" class="btn btn-outline-danger" value="Logout"> Выйти из
                                аккаунта
                            </button>
                        </form>
                    </div>
                </div>
            </div>

{% endif %}
    <br>
        <br>
     <div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>
     {% for post in object_list %}

                    <div style="color: whitesmoke">
                        <div class="d-flex">
                            <div class="p-2">
                                <img src="/media/{{ post.picture }}" width="250" height="170">
                            </div>
                            <div class="p-2">
                                <h2 style="color: #e4b101">{{ post.title }}</h2>
                                <p> {{ post.content}}</p>
                                <div class="p-2">
                                <img src="/media/{{ post.author.photo }}" width="120" height="70">
                            </div>
                                <p>Author: {{ post.author}}</p>
                                <p> Номер телефона: {{ post.author.phone_number }}
                                    <p>Email: {{ post.author.email }}</p>
                            <br>



                            </div>
                        </div>
                    </div>
                                {% endfor %}
     <nav aria-label="Page navigation example" style="min-height: 100%">
  <ul class="pagination">
   {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}
      <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
      {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
  {% endif %}
  </ul>

</nav>

{% endblock %}

templates/postcreate.html
{% extends 'base.html' %}

{% block content %}
   <div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>
    <div style="color: #e4b101; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%)">

        <form method="post" action="{% url 'create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success" value="Create product"> Create</button>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div style="color: #e4b101; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%)">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success" value="Registration"> Register</button>
        </form>

    </div>
    <div class="p-2">



        <form method="get" action= "{% url 'main' %}">


                <button type="submit" class="btn btn-warning" value="Update"> Back to main page </button>
            </form>
    </div>
{% endblock %}